`July 18, 2022`

# **Module 2: Python for Data Analysis**

## **Numpy**

[Numpy Documentation](https://numpy.org/doc/stable/numpy-user.pdf)

In [4]:
# Import library terlebih dahulu agar dapat menggunakan numpy
import numpy as np

### Membuat array

In [15]:
# Membuat 1D array menggunakan np.array

# np.array hanya dapat menampung satu tipe data saja
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [16]:
# Contoh ketika ada satu string di antara 4 int.
    # Maka, semua angka akan menjadi tipe data np.str (string)
arr_2 = np.array([1, 2, 'a', 4, 5])
arr_2

array(['1', '2', 'a', '4', '5'], dtype='<U11')

In [14]:
# Cek tipe data variabel arr
type(arr)

numpy.ndarray

In [17]:
# Cek tipe data variabel arr_2
type(arr_2)

numpy.ndarray

In [18]:
# Cek tipe data untuk item yang ada di dalam array
display(arr.dtype)
display(arr_2.dtype)

dtype('int32')

dtype('<U11')

In [21]:
# Membuat 1D array dari sebuah list

list_1d = [1, 2, 3, 4, 5]
print('List: ', list_1d)

# Konversi dari list ke array
arr_1d = np.array(list_1d)
arr_1d

List:  [1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

In [22]:
# Cek size yang dibutuhkan untuk list berisi 5 item (dalam byte)
import sys 

sys.getsizeof(list_1d)

120

In [23]:
# Cek size arr_1d
arr_1d.nbytes

20

In [32]:
# Membuat 2D array dari sebuah list
list_2d = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

display(list_2d)

# Konversi 2D list ke 2D array
arr_2d = np.array(list_2d)
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# Membuat 3D array dari sebuh list
list_3d = [
            [
                [1, 2],
                [3, 4],
                [5, 6]
            ],
            [
                [7, 8],
                [9, 10],
                [11, 12]
            ]
]

display(list_3d)

# Konversi ke 3D array
arr_3d = np.array(list_3d)
arr_3d

[[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### Arange

In [38]:
# Array berisi angka berurut menggunakan np.arange()

# Default mulai dari 0
# Sifatnya adalah 0 <= n < 10
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# np.arange memiliki konsep start stop step seperti di materi modul 1
np.arange(start=5, stop=20, step=2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
np.arange(5, 20, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

### Zeros

In [41]:
# Array berisi hanya angka 0 (np.zeros())

# Default dtype pada output adalah float
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [43]:
# Cek item dtype
type(x[0])

numpy.float64

In [44]:
# Kalau misalnya ingin mengganti tipe data pada output,
    # bisa menggunakan parameter dtype
x_int = np.zeros(5, dtype='int32')
x_int

array([0, 0, 0, 0, 0])

In [45]:
# Cek item dtype
type(x_int[0])

numpy.int32

In [54]:
# Cek shape dari sebuah array
display(x_int.shape)
display(type(x_int.shape))

(5,)

tuple

In [58]:
# np.zeros 2D

zeros_2d = np.zeros((5, 3)) # Angka pertama merepresentasikan jumlah baris
                            # Angka kedua merepresentasikan jumlah kolom
zeros_2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
# Cek shape. Outcomenya adalah 2D
zeros_2d.shape

(5, 3)

### Ones

- Generate array dengan value berupa angka 1 dengan menggunakan np.ones(.
- Semua sifatnya sama dengan np.zeros()

In [60]:
# Array berisi angka 1
np.ones(3)

array([1., 1., 1.])

In [61]:
np.ones(3, 'int32')

array([1, 1, 1])

In [63]:
ones_2d = np.ones((5, 3), 'int32') # Angka pertama merepresentasikan jumlah baris
                            # Angka kedua merepresentasikan jumlah kolom
ones_2d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [65]:
# Membuat array ones 3D
ones_3d = np.ones((5, 3, 2), 'int64')
ones_3d

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int64)

In [66]:
# Cek shape
ones_3d.shape

(5, 3, 2)

### Eye

In [69]:
# Array berisi angka 0 dengan angka 1 secara diagonal.
# Dalam linear algebra bisa disebut juga identity matrix.
    # Jadi, jika dikenakan operasi matrix dengan compatible matrix,
    # maka akan mengembalikan matrix yang sama.

# Compatible matrix --> Misal: jumlah kolom pada matrix pertama harus sama dengan jumlah
                              #jumlah baris pada matrix kedua.
                        
                        # Contoh: matrix 2x3 * 3x5 akan menghasilkan matrix 2x5

my_eye = np.eye(10, 2)
my_eye

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Linspace

In [70]:
# Array membagi sekian elemen dengan interval yang sama,
    # sesuai dengan range value yang didefinisikan

np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [71]:
np.linspace(99, 100, 50)

array([ 99.        ,  99.02040816,  99.04081633,  99.06122449,
        99.08163265,  99.10204082,  99.12244898,  99.14285714,
        99.16326531,  99.18367347,  99.20408163,  99.2244898 ,
        99.24489796,  99.26530612,  99.28571429,  99.30612245,
        99.32653061,  99.34693878,  99.36734694,  99.3877551 ,
        99.40816327,  99.42857143,  99.44897959,  99.46938776,
        99.48979592,  99.51020408,  99.53061224,  99.55102041,
        99.57142857,  99.59183673,  99.6122449 ,  99.63265306,
        99.65306122,  99.67346939,  99.69387755,  99.71428571,
        99.73469388,  99.75510204,  99.7755102 ,  99.79591837,
        99.81632653,  99.83673469,  99.85714286,  99.87755102,
        99.89795918,  99.91836735,  99.93877551,  99.95918367,
        99.97959184, 100.        ])

### Membuat array berisi angka random

**rand**


In [72]:
# rand() --> Generate angka random dari 0 sampai 1
np.random.rand(10)

array([0.64866892, 0.36920585, 0.9400343 , 0.26248838, 0.04506963,
       0.34112691, 0.66285059, 0.92750258, 0.83142217, 0.64112318])

In [74]:
rand_2d = np.random.rand(2, 5)
rand_2d

array([[0.49889705, 0.10782777, 0.63832293, 0.3964653 , 0.26296734],
       [0.0098299 , 0.23019888, 0.5413736 , 0.78398792, 0.71282141]])

In [75]:
rand_2d.shape

(2, 5)

**randn**

In [82]:
# randn() --> Array berisi angka random yang mengikuti pola standard normal distribution (z-distribution),
            # dengan nilai rata-rata mendekati 0 dan standard deviasi mendekati 1. 

randn_1d = np.random.randn(40)
randn_1d

array([-0.9206536 , -1.30289974, -0.14944172,  0.89892951,  0.72765213,
       -1.34739456, -0.59551658,  0.08656787, -0.03114106,  0.16011694,
       -1.46958815,  1.43889125,  1.00370584, -2.58489215, -0.08382517,
        0.58067755, -0.66504762, -1.35439847,  1.10731694,  0.99412886,
       -0.15596123, -0.08959825,  1.87815178, -0.58063261, -0.52718595,
       -0.45318241, -0.43784727, -0.65740202,  0.61604582, -0.016451  ,
        0.82389704, -0.69447993, -1.10325259,  1.33852884,  0.60193983,
        0.28899754, -0.19368999, -0.9257167 , -0.35830143, -1.42836475])

In [83]:
# Cek nilai mean
# Nilai akan mendekati 0
randn_1d.mean()

-0.13953292999347364

In [84]:
# Cek nilai standard deviation
# Nilai akan mendekati 1
randn_1d.std()

0.9373869231221414

**randint**

In [100]:
# randint() --> Array berisi angka random integer.
# Batas atas bersifat exclusive --> lower_bound <= n < upper_bound

np.random.randint(2, 20)

16

In [112]:
# Membuat array 2D dengan 2 baris dan 3 kolom menggunakan randint()
np.random.randint(2, 20, (2, 3))

array([[11, 17,  4],
       [18,  9,  6]])

## **Numpy Attributes & Methods**

**Shape**

In [115]:
# Shape 
arr_arange = np.arange(0, 12)
print(arr_arange)
print(arr_arange.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


**Reshape**

In [119]:
# Reshape dapat digunakan selama jumlah item sebelum dan sesudah transformasi 
    # tetaplah sama.

# Mengubah 1D array menjadi 2D array
arr_arange_reshape = arr_arange.reshape(3, 4)

print(arr_arange_reshape)
print()
print(arr_arange_reshape.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

(3, 4)


In [120]:
arr_arange.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [121]:
arr_arange.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [124]:
arr_arange.reshape(1, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [125]:
arr_arange.reshape(12, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [122]:
# Error karena ada perbedaan size antara sebelum dan sesudah reshape
arr_arange.reshape(2, 5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [123]:
# Mengubah array nD menjadi 1D secara cepat menggunakan .reshape(-1)

arr_reshape_back = arr_arange_reshape.reshape(-1)
arr_reshape_back

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**Methods**

In [130]:
arr_new = np.random.randint(20, 200, (5, 6))
arr_new

array([[128, 129, 160,  57, 162, 167],
       [175, 149, 152, 153, 148,  73],
       [ 65,  98,  76,  40,  59, 148],
       [ 50, 136,  62,  42, 102, 107],
       [182,  52,  48,  90, 181, 149]])

In [132]:
# Mencari nilai maksimum pada suatu array
arr_new.max()

182

In [133]:
# Mencari INDEX nilai maksimum pada suatu array
arr_new.argmax()

24

In [134]:
# Mencari nilai minimum pada suatu array
arr_new.min()

40

In [135]:
# Mencari INDEX nilai minimum pada suatu array
arr_new.argmin()

15

In [136]:
# Mengetahui tipe data dari elemen pada suatu array
arr_new.dtype

dtype('int32')

In [148]:
# TAMBAHAN
# Array structured
    # Jika ingin menampung data yang berbeda tipe datanya, harus ditampung ke 
        # sebuah list atau tuple misalnya.

# Jika ingin menampung data yang berbeda tipe datanya dan 
    # mendefinisikan dtype = 'object', maka tipe datanya 
    # akan secara otomatis diubah menjadi string semua atau <U..
mix_array = np.array([[5, 'saya', True], ['kamu', 10.5, 20]])
mix_array

array([['5', 'saya', 'True'],
       ['kamu', '10.5', '20']], dtype='<U32')

In [149]:
type(mix_array)

numpy.ndarray

In [156]:
print(mix_array[1][1])
print(type(mix_array[1][1]))

23
<class 'numpy.str_'>


In [150]:
mix_array[1][1] = 23
mix_array

array([['5', 'saya', 'True'],
       ['kamu', '23', '20']], dtype='<U32')

In [151]:
# Variasi kedua

# Jika parameter dtype = 'object' didefinisikan secara eksplisit,
    # maka tipe data untuk tiap item akan dikembalikan sesuai dengan tipe datanya.
mix_array_obj = np.array([[5, 'saya', True], ['kamu', 10.5, 20]], dtype='object')
mix_array_obj

array([[5, 'saya', True],
       ['kamu', 10.5, 20]], dtype=object)

In [152]:
type(mix_array_obj)

numpy.ndarray

In [155]:
print(mix_array_obj[1][1])
print(type(mix_array_obj[1][1]))

10.5
<class 'float'>


## **Indexing & Slicing**

In [158]:
arr = np.random.randint(100, 150, 15)
arr

array([115, 133, 137, 108, 103, 119, 122, 125, 102, 131, 103, 115, 105,
       101, 109])

In [159]:
# Indexing 1 element
arr[3]

108

In [161]:
# Slicing [start:stop:step] urutan maju
arr[0:10:3]

array([115, 108, 122, 131])

In [163]:
# Slicing [start:stop:step] urutan mundur
arr[8:0:-2]

array([102, 122, 103, 137])

In [164]:
# Mengganti nilai dari index tertentu
# Gunakan .copy untuk duplikasi variabel yang ingin dimodifikasi,
    # sehingga nilai yang ada pada variabel original tidak ikut berubah
arr_new = arr.copy()
arr_new[0:5] = 999
arr_new

array([999, 999, 999, 999, 999, 119, 122, 125, 102, 131, 103, 115, 105,
       101, 109])

In [165]:
arr

array([115, 133, 137, 108, 103, 119, 122, 125, 102, 131, 103, 115, 105,
       101, 109])

In [166]:
# Membuat array 2D
array_2d = np.array([[10, 15, 20], [25, 30, 35], [40, 45, 50]])
array_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [167]:
# Slicing baris index 1
array_2d[1]

array([25, 30, 35])

In [168]:
# Slicing baris index 0, lalu slicing kolom index 1
array_2d[0][1] # Template-nya adalah [baris][kolom]

15

In [169]:
# Slicing hanya kolom index 1
array_2d[:, 1] # [baris, kolom]

array([15, 30, 45])

In [170]:
# Slicing hanya baris index 0 dan 1, lalu kolom index 0 saja
array_2d[:2, :1] # [baris, kolom]

array([[10],
       [25]])

**Fancy Indexing**

- Fancy indexing digunakan untuk indexing index yang tidak berurutan.
- Ditandai dengan penggunaan double square brackets.
- Urutan element yang mau di-indexing bebas.
- Tidak bisa melakukan slicing pada fancy indexing.

In [171]:
array_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [201]:
# Jika seperti ini, kita berarti hanya mendefinisikan index barisnya saja
random = array_2d[[2, 1, 0, 0, 1, 2]]
random

array([[40, 45, 50],
       [25, 30, 35],
       [10, 15, 20],
       [10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [178]:
random.shape

(6, 3)

In [192]:
# Kalau kita mau memiliki kolomnya juga secara spesifik,
    # definisikan di dalam square bracket terpisah.
    # Template --> nama_variabel[[baris], [kolom]]

array_2d[[1, 2], [0]]

array([25, 40])

In [187]:
# Angka index baris akan dipasangkan dengan angka index kolom
    # sesuai dengan urutannya.
array_2d[[1, 2], [0, 2]]

array([25, 50])

In [193]:
# baris index 1 dengan kolom index 0
# baris index 1 dengan kolom index 1
# baris index 2 dengan kolom index 2
array_2d[[1, 1, 2], [0, 1, 2]]

array([25, 30, 50])

In [199]:
array_2d[[1, 2, 0], [0, 0, 0]]

array([25, 40, 10])

## **Conditional Selection**

In [206]:
arr_cond = array_2d.reshape(-1)
arr_cond

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [207]:
# Jika dituliskan seperti ini, maka akan mengembalikan Boolean
arr_cond > 30

array([False, False, False, False, False,  True,  True,  True,  True])

In [209]:
# Dimasukkan ke dalam sebuah variabel
x = arr_cond > 30

In [208]:
# Jika ingin menampilkan nilainya, maka bisa digunakan konsep indexing
arr_cond[arr_cond > 30]

array([35, 40, 45, 50])

In [210]:
arr_cond[x]

array([35, 40, 45, 50])

## **Arithmetic 1D**

In [211]:
arr = np.arange(22, 34)
arr

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [212]:
# Menambahkan 3 pada setiap item di array arr
arr + 3

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36])

In [213]:
# Mengalikan 2 pada setiap item di array arr
arr * 2

array([44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66])

## **Arithmetic 2D**

In [214]:
array_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [215]:
array_2d * 2

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [216]:
# Error, gagal dalam broadcasting karena shape antara kedua array
    # tidak sama (baik itu dalam baris atau kolom)
array_2d * arr

ValueError: operands could not be broadcast together with shapes (3,3) (12,) 

In [217]:
arr_broadcast = np.arange(0, 3)
arr_broadcast

array([0, 1, 2])

In [222]:
arr_broadcast.shape

(3,)

In [223]:
array_2d.shape

(3, 3)

In [220]:
arr_broadcast * array_2d

array([[  0,  15,  40],
       [  0,  30,  70],
       [  0,  45, 100]])

In [221]:
# Opsi 1 transpose (.T)
arr_broadcast * array_2d.T

array([[  0,  25,  80],
       [  0,  30,  90],
       [  0,  35, 100]])

In [225]:
# Opsi 2 transpose
arr_broadcast * array_2d.transpose()

array([[  0,  25,  80],
       [  0,  30,  90],
       [  0,  35, 100]])

## **Functions**

In [226]:
# Mencari nilai akar kuadrat dengan np.sqrt
np.sqrt(array_2d)

array([[3.16227766, 3.87298335, 4.47213595],
       [5.        , 5.47722558, 5.91607978],
       [6.32455532, 6.70820393, 7.07106781]])

In [227]:
# Nilai sinous
np.sin(array_2d)

array([[-0.54402111,  0.65028784,  0.91294525],
       [-0.13235175, -0.98803162, -0.42818267],
       [ 0.74511316,  0.85090352, -0.26237485]])

In [228]:
# Tangent
np.tan(array_2d)

array([[ 0.64836083, -0.8559934 ,  2.23716094],
       [-0.13352641, -6.4053312 ,  0.47381472],
       [-1.11721493,  1.61977519, -0.27190061]])

In [229]:
# Natural logarithmic (ln, base e) --> Euler's number
np.log(array_2d)

array([[2.30258509, 2.7080502 , 2.99573227],
       [3.21887582, 3.40119738, 3.55534806],
       [3.68887945, 3.80666249, 3.91202301]])

In [230]:
# Exponential
np.exp(array_2d)

array([[2.20264658e+04, 3.26901737e+06, 4.85165195e+08],
       [7.20048993e+10, 1.06864746e+13, 1.58601345e+15],
       [2.35385267e+17, 3.49342711e+19, 5.18470553e+21]])

In [232]:
# Insert
# Menyelipkan sebuah element pada index tertentu
np.insert(arr_broadcast, 1, 9999) # Syntax: var_name, index, new_value

array([   0, 9999,    1,    2])

In [233]:
array_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [244]:
# Menambahkan 1 baris pada 2D array
# axis = 0 merepresentasikan baris
np.insert(array_2d, 0, [1, 1, 1], axis=0)

array([[ 1,  1,  1],
       [10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [243]:
# Menambahkan 1 kolom pada 2D array
# axis = 1 merepresentasikan kolom
np.insert(array_2d, 0, [1, 1, 1], axis=1)

array([[ 1, 10, 15, 20],
       [ 1, 25, 30, 35],
       [ 1, 40, 45, 50]])

In [245]:
# Kalau axis = None, berarti akan dijadikan 1D array (flattened)
np.insert(array_2d, 0, [1, 1, 1], axis=None)

array([ 1,  1,  1, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [246]:
# Menghapus element pada index tertentu
np.delete(arr_broadcast, 0) # Menghapus element index ke-0

array([1, 2])

In [247]:
# Menmabahkan elemen pada index terakhir
np.append(arr_broadcast, 2000)

array([   0,    1,    2, 2000])

In [253]:
# Menggabungkan 2 array terpisah menjadi 1 array

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 20, 30]])

np.concatenate((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [257]:
np.concatenate((a.T, b))

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [10, 20, 30]])

In [258]:
# np.where untuk filtering conditions
np.where(array_2d >=30, 100, array_2d) # Syntax: np.where(condition, new_value, target_object)

array([[ 10,  15,  20],
       [ 25, 100, 100],
       [100, 100, 100]])

In [267]:
# Jika value diubah menjadi string, maka semua int menjadi string
np.where(array_2d >=30, 'A', array_2d)

array([['10', '15', '20'],
       ['25', 'A', 'A'],
       ['A', 'A', 'A']], dtype='<U11')

In [266]:
# Jika value diubah dengan nilai Boolean, maka akan dikonversi menjadi 0 (False)
    # atau 1 (True), dan nilai lainnya tetap menjadi int.
x_where = np.where(array_2d >=30, False, array_2d)
x_where

array([[10, 15, 20],
       [25,  0,  0],
       [ 0,  0,  0]])

In [265]:
x_where[2].dtype

dtype('int32')